services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'app_spring'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
  spring-backend:
    build:
        context: ./
        dockerfile: ./backend/Dockerfile
    container_name: spring-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
  vite-frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: vite-frontend
    ports:
      - "5173:5173"
    depends_on:
      - spring-backend
    restart: always

volumes:
  data-mysql:
    